### ISSUE TITLE
Chassis objects are not very DRY

### ISSUE THREAD

**Issue by notCalle** [saab-simc-admin/palletjack#13]
Chassis objects are not very DRY, with basically the same information already present in the name being repeated in `identity.yaml`. I would suggest something along the lines of:

`chassis/<vendor>:<dash-separated-model>:<serial>`

``` yaml
- chassis.vendor:
  - synthesize_regexp:
      sources: &pallet_chassis
        chassis:
          key: "pallet.chassis"
          regexp: "^(?<vendor>[^:]*):((?<line>[^:-]*)-)?((?<series>[^:-]*)-)?(?<model>[^:]*):(?<serial>[^:]*)$"
      produce: "#[vendor]"
- chassis.model:
  - synthesize_regexp:
      sources: *pallet_chassis
      produce:
        - "#[line] #[series] #[model]"
        - "#[line] #[model]"
        - "#[model]"
- chassis.serial:
  - synthesize_regexp:
      sources: *pallet_chassis
      produce: "#[serial]"
```

The DRY source regexp YAML reference magic requires #9 to work.
