### ISSUE TITLE
Wrong value inherited for net.layer2.name in ipv4_interface

### ISSUE THREAD

**Issue by creideiki** [saab-simc-admin/palletjack#31]
In the example warehouse, we have:

``` yaml
net:
  layer2:
    name: eth0
```

Which can be seen when you do `dump_pallet -w examples/warehouse/ -t phy_nic 52:54:00:12:34:56`:

``` yaml
net:
  layer2:
    address: '52:54:00:12:34:56'
    name: eth0
```

However, when you dump the `ipv4_interface` running on that `phy_nic`, the name is wrong: `dump_pallet -w examples/warehouse/ -t ipv4_interface 192.168.0.2`

``` yaml
net:
  layer2:
    address: '52:54:00:12:34:56'
    name: em1
```

`em1` is the name of the underlying `phy_nic`, `14:18:77:ab:cd:ef`.
