### ISSUE TITLE
Need CNAME records in DNS

### ISSUE THREAD

**Issue by notCalle** [saab-simc-admin/palletjack#48]
First we need to model this type of information in a palletjack warehouse, then palletjack2knot needs to be enhanced to generate CNAME records.

**Comment by notCalle** [comment]
Improper service aliases:

``` yaml
net:
  dns:
    cname:
      kickstart: installserver1
```

Proper service definitions:

``` yaml
net:
  dns:
    srv:
      - service: xmpp-server
        protocol: tcp
        port: 5269
        priority: 0 # default 0 unless given
        weight: 0 # default 0 unless given
        target: xmpp1.example.com. # dot terminated fqdn
      - service: xmpp-server
        protocol: tcp
        port: 5269
        target: xmpp2
```

Interface specific aliases:

``` yaml
net:
  dns:
    name: switch4711
    alias:
      - sw4711
```
